[package]
name = "baek_2839"
version = "0.1.0"
authors = ["Jiseok CHOI <jiseok@hyperithm.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
